# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: python:2.7.15

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: setup python defaultencoding
          command: |
            python -c "import sys; print sys.getdefaultencoding()"
            path=`python -c "import site; print site.getsitepackages()[0]"`/sitecustomize.py
            echo $path
            echo "import sys; sys.setdefaultencoding('utf-8')" > $path
            cat $path
            python -c "import sys; print sys.getdefaultencoding()"

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python random_words.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
